name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ${POSTGRES_USER}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
          POSTGRES_DB: ${POSTGRES_DB}
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: docker-compose up -d --build

      - name: Wait for API to be healthy
        run: |
          for i in {1..30}; do
            curl --fail http://localhost:8000/docs && break
            echo "Waiting for API..."
            sleep 2
          done

      - name: Run flake8 lint
        run: docker exec market_api flake8 app/

      - name: Run pytest tests
        run: docker exec -e PYTHONPATH=/app market_api pytest --maxfail=1 --disable-warnings -q

      - name: Tear down
        if: always()
        run: docker-compose down -v