name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t market_api:ci .


      - name: Run flake8 lint
        run: docker run --rm market_api:ci flake8 app/

      - name: Run pytest tests
        run: docker run --rm market_api:ci pytest --maxfail=1 --disable-warnings -q